# fly.toml app configuration file generated for pokepoke on 2023-10-18T22:21:09+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pokepoke"
primary_region = "arn"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]

[experimental]
  auto_rollback = true

[deploy]
  release_command = "npm run build"
  strategy = "rolling"

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = 5000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]
